tutoria net core/ViewModels/CrearRolViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace tutoria_net_core.ViewModels
{
    public class CrearRolViewModel
    {
        [Required(ErrorMessage ="Este campo es obligatorio")]
        [Display(Name = "Rol")]
        public string NombreRol { get; set; }
    }
}

tutoria net core/ViewModels/EditarRolViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace tutoria_net_core.ViewModels
{
    public class EditarRolViewModel
    {

        public string Id { get; set; }
        public EditarRolViewModel()
        {
            Usuarios = new List<string>();
        }


        [Required(ErrorMessage = "El nombre del rol es obligatorio")]
        public string RolNombre { get; set; }

        public List<string> Usuarios { get; set; }
    }
}

tutoria net core/Controllers/AdministracionController.cs
using tutoria_net_core.Models;
using tutoria_net_core.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Ejemplo1.Controllers
{
    [Authorize(Roles = "Administrador,Dios")]//establece que solo los usuarios asignados a estos roles pueden ver las pantallas que hay en este controller

    public class AdministracionController : Controller
    {
        private readonly RoleManager<IdentityRole> gestionRoles;
        private readonly UserManager<UsuarioAplicacion> gestionUsuarios;
        private readonly ILogger<AdministracionController> log;


        public AdministracionController(RoleManager<IdentityRole> gestionRoles,
                                        UserManager<UsuarioAplicacion> gestionUsuarios,
                                       ILogger<AdministracionController> log)
        {
            this.gestionRoles = gestionRoles;
            this.gestionUsuarios = gestionUsuarios;
            this.log = log;
        }

        [HttpGet]
        [Route("Administracion/CrearRol")]
        [AllowAnonymous]
        public IActionResult CrearRol()
        {
            return View();
        }

        [HttpPost]
        [Route("Administracion/CrearRol")]
        [AllowAnonymous]
        public async Task<IActionResult> CrearRol(CrearRolViewModel model)
        {
            if (ModelState.IsValid)
            {
                IdentityRole identityRole = new IdentityRole
                {
                    Name = model.NombreRol
                };

                IdentityResult result = await gestionRoles.CreateAsync(identityRole);

                if (result.Succeeded)
                {
                    return RedirectToAction("index", "home");
                }

                foreach (IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }

            return View(model);
        }

       [HttpGet]
        [Route("Administracion/Roles")]
        [AllowAnonymous]
        public IActionResult ListaRoles()
        {
            var roles = gestionRoles.Roles;
            return View(roles);
        }
        
        [HttpGet]
        [Route("Administracion/EditarRol")]
        [AllowAnonymous]
        public async Task<IActionResult> EditarRol(string id)
                {
                    //Buscamos el rol por el id
                    var rol = await gestionRoles.FindByIdAsync(id);

                    if (rol == null)
                    {
                        ViewBag.ErrorMessage = $"Rol con el Id = {id} no fue encontrado";
                        return View("Error");
                    }
                    //obtenemos todos los usuarios para ese rol
                    var model = new EditarRolViewModel
                    {
                        Id = rol.Id,
                        RolNombre = rol.Name
                    };

            // Obtenemos todos los usuarios
                   var userList = gestionUsuarios.Users.ToList();
                    foreach (var usuario in userList)
                    {
                        if (await gestionUsuarios.IsInRoleAsync(usuario, rol.Name))
                        {

                            model.Usuarios.Add(usuario.UserName);
                        }
                    }

                    return View(model);
                }

      

                [HttpPost]
                [Route("Administracion/EditarRol")]
        //[Authorize(Policy = "EditarRolPolicy")]
        [AllowAnonymous]
        public async Task<IActionResult> EditarRol(EditarRolViewModel model)
                {
                    var rol = await gestionRoles.FindByIdAsync(model.Id);

                    if (rol == null)
                    {
                        ViewBag.ErrorMessage = $"Rol con el Id = {model.Id} no fue encontrado";
                        return View("Error");
                    }
                    else
                    {// si existe pasamos el nombre del rol al objeto que vamos amodidicar
                        rol.Name = model.RolNombre;

                        var resultado = await gestionRoles.UpdateAsync(rol);

                        if (resultado.Succeeded)
                        {
                            return RedirectToAction("ListaRoles");
                        }

                        foreach (var error in resultado.Errors)
                        {
                            ModelState.AddModelError("", error.Description);
                        }

                        return View(model);
                    }
                }

                [HttpPost]
                [Route("Administracion/BorrarRol")]
                [Authorize(Policy = "BorrarRolPolicy")]
        [AllowAnonymous]
        public async Task<IActionResult> BorrarRol(string id)
                {
                    var rol = await gestionRoles.FindByIdAsync(id);

                    if (rol == null)
                    {
                        ViewBag.ErrorMessage = $"Rol con el Id = {id} no fue encontrado";
                        return View("Error");
                    }
                    else
                    {
                        try
                        {
                            var result = await gestionRoles.DeleteAsync(rol);

                            if (result.Succeeded)
                            {
                                return RedirectToAction("ListaRoles");
                            }

                            foreach (var error in result.Errors)
                            {
                                ModelState.AddModelError("", error.Description);
                            }

                            return View("ListaRoles");
                        }
                        // Si da este tipo de excepcion sabemos que no podemos elimiar el rol porque tiene usuarios
                        catch (DbUpdateException ex)
                        {
                            log.LogError($"Se produjo un error al borrar el rol: {ex}");
                            //Pasamos el titulo del error y el mensage
                            ViewBag.ErrorTitle = $"El rol {rol.Name} está siendo utilizado";
                            ViewBag.ErrorMessage = $"El rol {rol.Name}  no puede ser borrado porque contiene usuarios.Antes de borrar el rol quita los usuarios de dicho rol.";
                            return View("ErrorGenerico");
                        }

                    }
                }
     

              [HttpGet]
              [Route("Administracion/EditarUsuarioRol")]
        [AllowAnonymous]
        public async Task<IActionResult> EditarUsuarioRol(string rolId)
              {
                  ViewBag.roleId = rolId;

                  var role = await gestionRoles.FindByIdAsync(rolId);

                  if (role == null)
                  {
                      ViewBag.ErrorMessage = $"Rol con el Id = {rolId} no fue encontrado";
                      return View("Error");
                  }

                  var model = new List<UsuarioRolModelo>();
            // Obtenemos todos los usuarios
            var userList = gestionUsuarios.Users.ToList();

            foreach (var user in userList)
                  {
                      var usuarioRolModelo = new UsuarioRolModelo
                      {
                          UsuarioId = user.Id,
                          UsuarioNombre = user.UserName
                      };

                      if (await gestionUsuarios.IsInRoleAsync(user, role.Name))
                      {
                          usuarioRolModelo.EstaSeleccionado = true;
                      }
                      else
                      {
                          usuarioRolModelo.EstaSeleccionado = false;
                      }

                      model.Add(usuarioRolModelo);
                  }

                  return View(model);
              }

              [HttpPost]
              [Route("Administracion/EditarUsuarioRol")]
        [AllowAnonymous]
        public async Task<IActionResult> EditarUsuarioRol(List<UsuarioRolModelo> model,
                                              string rolId)
              {
                  var rol = await gestionRoles.FindByIdAsync(rolId);

                  if (rol == null)
                  {
                      ViewBag.ErrorMessage = $"Rol con el Id = {rolId} no fue encontrado";
                      return View("Error");
                  }

                  for (int i = 0; i < model.Count; i++)
                  {
                      var user = await gestionUsuarios.FindByIdAsync(model[i].UsuarioId);

                      IdentityResult result = null;

                      if (model[i].EstaSeleccionado && !(await gestionUsuarios.IsInRoleAsync(user, rol.Name)))//los selecionados los agregamos a base de datos
                      {
                          result = await gestionUsuarios.AddToRoleAsync(user, rol.Name);
                      }
                      else if (!model[i].EstaSeleccionado && await gestionUsuarios.IsInRoleAsync(user, rol.Name))// los no selecionados los borramos
                      {
                          result = await gestionUsuarios.RemoveFromRoleAsync(user, rol.Name);
                      }
                      else
                      {
                          continue;
                      }

                      if (result.Succeeded)
                      {
                          if (i < (model.Count - 1))
                              continue;
                          else

tutoria net core/Views/Administracion/CrearRol.cshtml
@model CrearRolViewModel

@{
    Layout = "~/Views/share/_Layout.cshtml";
    ViewBag.Title = "Crear nuevo rol";
}

    <h1>Crear nuevo rol</h1>

<form asp-action="CrearRol" method="post" class="mt-3">
    <div asp-validation-summary="All" class="text-danger">
    </div>
    <div class="form-group row">
        <label asp-for="NombreRol" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="NombreRol" class="form-control" placeholder="Name">
            <span asp-validation-for="NombreRol" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary" style="width:auto">
                Crear Rol
            </button>
        </div>
    </div>
</form>

tutoria net core/Views/Administracion/EditarRol.cshtml
@model EditarRolViewModel

@{
    Layout = "~/Views/share/_Layout.cshtml";
    ViewBag.Title = "Editar Rol";


}

    <h1 style="position: relative;">Editar Rol</h1>

<form method="post" class="mt-3">
    <div class="form-group row">
        <label asp-for="Id" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Id" disabled class="form-control">
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="RolNombre" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="RolNombre" class="form-control">
            <span asp-validation-for="RolNombre" class="text-danger"></span>
        </div>
    </div>

    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary" style="width:auto">Editar</button>
            <a asp-action="ListRoles" class="btn btn-primary" style="width:auto" >Cancelar</a>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            <h3>Usuarios en este rol</h3>
        </div>
        <div class="card-body">
            @if (Model.Usuarios.Any())
            {

                for (int i = 0; i < Model.Usuarios.Count; i++)
                {
                    <h5 class="card-title">@Model.Usuarios[i]</h5>
                    
                }
           
            }
            else
            {
                <h5 class="card-title">Ninguno por ahora</h5>
            }
        </div>
        <div class="card-footer">
            <a asp-controller="Administracion" asp-action="EditarUsuarioRol"
                 asp-route-rolId="@Model.Id" class="btn btn-primary" style="width:auto">
                Crear o borrar usuario 
            </a>
        </div>
    </div>
</form>

tutoria net core/Views/Administracion/EditarUsuarioRol.cshtml
@model List<UsuarioRolModelo>


@{
    var roleId = ViewBag.roleId;
    Layout = "~/Views/share/_Layout.cshtml";
}

<form method="post">
    <div class="card">
        <div class="card-header">
            <h2>Agregar o borrar usuarios a este rol</h2>
        </div>
        <div class="card-body">
            @for (int i = 0; i < Model.Count; i++)
            {
                <div class="form-check m-1">
                    <input type="hidden" asp-for="@Model[i].UsuarioId" />
                    <input type="hidden" asp-for="@Model[i].UsuarioNombre" />
                    <input asp-for="@Model[i].EstaSeleccionado" class="form-check-input" />
                    <label class="form-check-label" asp-for="@Model[i].EstaSeleccionado">
                        @Model[i].UsuarioNombre
                    </label>
                </div>
            }
        </div>
        <div class="card-footer">
            <input type="submit" value="Actualizar" class="btn btn-primary"
                   style="width:auto" />
            <a asp-action="EditarRol" asp-route-id="@roleId"
               class="btn btn-primary" style="width:auto">Cancelar</a>
        </div>
    </div>
</form>

tutoria net core/Views/Administracion/ListaRoles.cshtml
@model IEnumerable<IdentityRole>
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService authorizationService;


@{
    Layout = "~/Views/share/_Layout.cshtml";
    ViewBag.Title = "Listado de roles";
}

<h1>Listado de roles</h1>

@if (Model.Any())
{
    <a class="btn btn-primary mb-3" style="width:auto" asp-action="CrearRol"
       asp-controller="Administracion">Crear nuevo rol</a>

    foreach (var rol in Model)
    {
        <div class="card mb-3">
            <div class="card-header">
                Rol identificador : @rol.Id
            </div>
            <div class="card-body">
                <h5 class="card-title">@rol.Name</h5>
            </div>
            <div class="card-footer">
                <form method="post" asp-action="BorrarRol" asp-route-id="@rol.Id">
                    
                    @*@if ((await authorizationService.AuthorizeAsync(User, "EditarRolPolicy")).Succeeded)
                    {*@
                        <a asp-controller="Administracion" asp-action="EditarRol"
                           asp-route-id="@rol.Id" class="btn btn-primary">
                            Editar
                        </a>
 @*                   }*@

                    <span id="confirmBorrarSpan_@rol.Id" style="display:none">
                        <span>Seguro que quieres borrar?</span>
                        <button type="submit" class="btn btn-danger">Si</button>
                        <a href="#" class="btn btn-primary"
                           onclick="confirmBorrar('@rol.Id', false)">No</a>
                    </span>

                    <span id="BorrarSpan_@rol.Id">
                        <a href="#" class="btn btn-danger"
                           onclick="confirmBorrar('@rol.Id', true)">Borrar</a>
                    </span>
                </form>
            </div>
        </div>
    }
}
else
{
    <div class="card">
        <div class="card-header">
            Todavia no hay roles creados
        </div>
        <div class="card-body">
            <h5 class="card-title">
                Usa este boton para crear un rol
            </h5>
            <a class="btn btn-primary" style="width:auto"
               asp-controller="Administracion" asp-action="CrearRol">
                Crear Rol
            </a>
        </div>
    </div>
}

@section Scripts {
    <script src="~/js/MiScript.js"></script>
}